using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Nomina.WebForms.App_Code.Models.Payroll.DTO.Enum.PayrollElectronic.AL
{
    public enum EnumFieldConfigurationPayroll
    {
        Empleado_Datosbásicos_Clase_documento_1 = 1,
        Empleado_Datosbásicos_Tipo_de_nota_2 = 2,
        Empleado_Datosbásicos_Prefijo_3 = 3,
        Empleado_Datosbásicos_Consecutivo_4 = 4,
        Empleado_Datosbásicos_Tipo_Documento_5 = 5,
        Empleado_Datosbásicos_Número_Documento_6 = 6,
        Empleado_Datosbásicos_Sueldo_7 = 7,
        Empleado_Datosbásicos_Sueldo_trabajado_8 = 8,
        Empleado_Datosbásicos_Salario_integral_9 = 9,
        Empleado_Datosbásicos_Días_laborados_10 = 10,
        Empleado_Datosbásicos_Fecha_Ingreso_11 = 11,
        Empleado_Datosbásicos_Fecha_Retiro_12 = 12,
        Datos_empresa_Datosbásicos_País_13 = 13,
        Datos_empresa_Datosbásicos_Departamento_14 = 14,
        Datos_empresa_Datosbásicos_Ciudad_15 = 15,
        Datos_empresa_Datosbásicos_Dirección_16 = 16,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Periodo_Nómina_17 = 17,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Fecha_inicio_pago_NE_18 = 18,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Fecha_fin_pago_NE_19 = 19,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Fecha_de_pago_1_20 = 20,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Fecha_de_pago_2_21 = 21,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Fecha_de_pago_3_22 = 22,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Fecha_de_pago_4_23 = 23,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Forma_de_pago_24 = 24,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Método_de_pago_25 = 25,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Banco_26 = 26,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Tipo_Cuenta_27 = 27,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Número_Cuenta_28 = 28,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_Tipo_Moneda_29 = 29,
        Datos_generales_de_Nómina_Electrónica_Datosdepago_TRM_30 = 30,
        Devengos_Transporte_Auxilio_Transporte_31 = 31,
        Devengos_Transporte_Viático_Manutención_Alojamiento_32 = 32,
        Devengos_Transporte_Viático_Manutención_Alojamiento_no_salarial_33 = 33,
        Devengos_Comisiones_Comisión_34 = 34,
        Devengos_Auxilios_Auxilio_salarial_35 = 35,
        Devengos_Auxilios_Auxilio_no_salarial_36 = 36,
        Devengos_Bonificaciones_Bonificación_salarial_37 = 37,
        Devengos_Bonificaciones_Bonificacion_no_salarial_38 = 38,
        Devengos_Primas_Cantidad_de_días_39 = 39,
        Devengos_Primas_Pago_40 = 40,
        Devengos_Primas_Pago_no_salarial_41 = 41,
        Devengos_Cesantías_Pago_42 = 42,
        Devengos_Cesantías_Porcentaje_43 = 43,
        Devengos_Cesantías_Pago_Intereses_44 = 44,
        Devengos_Compensaciones_Compensación_Ordinaria_45 = 45,
        Devengos_Compensaciones_Compensación_Extraordinaria_46 = 46,
        Devengos_BonoElectrónicoodePapeldeServicio_Cheque_Tarjeta_Vale_Pago_Salarial_47 = 47,
        Devengos_BonoElectrónicoodePapeldeServicio_Cheque_Tarjeta_Vale_Pago_no_Salarial_48 = 48,
        Devengos_BonoElectrónicoodePapeldeServicio_Cheque_Tarjeta_Vale_Pago_Alimentación_Salarial_49 = 49,
        Devengos_BonoElectrónicoodePapeldeServicio_Cheque_Tarjeta_Vale_Pago_Alimentación_no_Salarial_50 = 50,
        Devengos_Pagoterceros_Pago_Tercero_51 = 51,
        Devengos_Anticipos_Anticipo_52 = 52,
        Devengos_Anticipos_Dotación_53 = 53,
        Devengos_Anticipos_Apoyo_Sostenimiento_54 = 54,
        Devengos_Anticipos_Teletrabajo_55 = 55,
        Devengos_Anticipos_Bonificación_Retiro_56 = 56,
        Devengos_Anticipos_Indemnización_57 = 57,
        Devengos_Anticipos_Reintegro_58 = 58,
        Deducciones_Salud_Porcentaje_59 = 59,
        Deducciones_Salud_Deducción_60 = 60,
        Deducciones_Pensión_Porcentaje_61 = 61,
        Deducciones_Pensión_Deducción_62 = 62,
        Deducciones_FondodeSeguridadPensional_Porcentaje_63 = 63,
        Deducciones_FondodeSeguridadPensional_Deducción_Fondo_Solidaridad_Pensional_64 = 64,
        Deducciones_FondodeSeguridadPensional_Porcentaje_Fondo_Subsistencia_65 = 65,
        Deducciones_FondodeSeguridadPensional_Deducción_Fondo_Subsistencia_66 = 66,
        Deducciones_Sindicato_Porcentaje_67 = 67,
        Deducciones_Sindicato_Deducción_68 = 68,
        Deducciones_Sanciones_Sanción_Pública_69 = 69,
        Deducciones_Sanciones_Sanción_Privada_70 = 70,
        Deducciones_PagoTercero_PagoTercero_71 = 71,
        Deducciones_Anticipo_Anticipo_72 = 72,
        Deducciones_Otrasdeducciones_Otra_Deducción_73 = 73,
        Deducciones_Otrasdeducciones_Pensión_Voluntaria_74 = 74,
        Deducciones_Otrasdeducciones_Retención_Fuente_75 = 75,
        Deducciones_Otrasdeducciones_AFC_Ahorro_Fomento_a_la_contrucción_76 = 76,
        Deducciones_Otrasdeducciones_Cooperativa_77 = 77,
        Deducciones_Otrasdeducciones_Embargo_Fiscal_78 = 78,
        Deducciones_Otrasdeducciones_Plan_Complementario_79 = 79,
        Deducciones_Otrasdeducciones_Educación_80 = 80,
        Deducciones_Otrasdeducciones_Reintegro_81 = 81,
        Deducciones_Otrasdeducciones_Deuda_82 = 82,
        Total_Nómina_Totales_Redondeo_83 = 83,
        Total_Nómina_Totales_Devengados_Total_84 = 84,
        Total_Nómina_Totales_Deducciones_Total_85 = 85,
        Total_Nómina_Totales_Comprobante_Total_86 = 86,
        Notas_documento_Notas_Observación_87 = 87
    }
}